language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database stocks_test;" -U postgres

#set some environment variables
env:
  - TEST_DATABASE_URL='postgres://127.0.0.1:5432/stocks_test'

# command to install dependencies
install:
  - pip install -e .[testing]

# commands to run tests
script:
  - pytest

notifications:
  email: false